<?xml version= '1.0' encoding= 'UTF-8' ?>
<!--Copyright © 2018, Oracle and/or its affiliates. All rights reserved.

The Universal Permissive License (UPL), Version 1.0
-->
<wsdl:definitions
     name="HCMDataLoader"
     targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="HcmHdlSvc">
        <plnk:role name="HCMDataLoader" portType="tns:HCMDataLoader"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/"
         location="HCMDataLoader.wsdl"/>
</wsdl:definitions>
